export const Routes = {
  // pages
  DashboardOverview: { path: "/" },
  Presentation: { path: "/pr" },
  Reports: { path: "/reports" },
  Merchants: { path: "/merchants" },
  Usermanagement: { path: "/user-management" },
  Transactions: { path: "/transactions" },
  Services: { path: "/services" },
  Channels: { path: "/channels" },
  Upgrade: { path: "/upgrade" },
  Billing: { path: "/examples/billing" },
  Invoice: { path: "/examples/invoice" },
  Signin: { path: "/auth/sign-in" },
  Signup: { path: "/auth/sign-up" },
  ForgotPassword: { path: "/redirect/forgot-password" },
  ResetPassword: { path: "/redirect/reset-password" },
  Lock: { path: "/redirect/lock" },
  NotFound: { path: "/error/404" },
  ServerError: { path: "/error/500" },
};
